### ISSUE TITLE
Question about autograd of pytorch.

### ISSUE THREAD

**Issue by Jackie-Chou** [dragen1860/MAML-Pytorch#11]
https://github.com/dragen1860/MAML-Pytorch/blob/75a7d7502b73e2bff17af492502737932994678f/maml.py#L399
Hi dragen:
    I have a question about the [autograd](https://pytorch.org/docs/stable/notes/autograd.html) mechanism of pytorch. It seems to me that pytorch doesn't support high-order gradient since it builds the graph during forward pass, while computes the gradients by reverse passing the graph without expanding it, thus the gradient variable actually has no link to the origin variable so we cant further compute its gradient w.r.t. the origin var.. However in the above part of the code, where the meta update is conducted, seems no special mechanism is used so I think the update doesn't consider high-order gradient formed by K times inner loop.
    To further demonstrate the problem, I write a [simple demo](https://gist.github.com/Jackie-Chou/949ada83fe5427073a6f1a34cb9009c1).

**Comment by Jackie-Chou** [comment]
My bad. After further reading the original paper and I find the first-order approximation mentioned in Sec 5.2. Experiment results show that the approximation is good enough as well as easy to implement. :)
Thank u for the great code.

**Comment by dragen1860** [comment]
haha, Pytorch support 2nd derivate from version 0.2.
actually, my code has a potential bug in Line 399, maml.py.

**Comment by dragen1860** [comment]
pls refer to this issue: https://github.com/dragen1860/MAML-Pytorch/issues/6
