### ISSUE TITLE
miniImagenet experiments

### ISSUE THREAD

**Issue by silverbottlep** [dragen1860/MAML-Pytorch#15]
Hi, thanks for sharing your code, BTW, I tried with the most recent version, but I couldn't get the same results as reported, 5-way 1-shot. I could get up to ~45% accs, do you have any idea?

**Comment by dragen1860** [comment]
hi @silverbottlep , according to latest version, it's easy to achieve 46.2%on 5-way-1shot, mini-imagenet.
To achieve 48% from original paper, maybe more trivial tricks needed.
