### ISSUE TITLE
Previous version

### ISSUE THREAD

**Issue by yqu1** [dragen1860/MAML-Pytorch#2]
Hi, I was trying to use code from your previous version. I was wondering what were the problems in the previous version and were you able to successfully replicate the omniglot experiment?

**Comment by dragen1860** [comment]
hi, I recently found the first version of my code has an definitely distinct implementation, and I never realised it until the paper "repitle":https://blog.openai.com/reptile/ published. That's to say, I already implemented the reptile version but i have not published my approach before the paper.
Concisely:
the disparity of previous and current is:
1. previous: theta = theta + meta_lr * (w - theta_pi)
2. current: theta = theta - meta_lr * grad(Loss on theta_pi, theta)

**Comment by yqu1** [comment]
Thanks, the previous version (reptile) you are talking about is the one with the MetaLearner and Learner class, which you completely erased from the repository, right?  were you able to achieve the accuracy described in the MAML paper for the omniglot experiment with the reptile implementation then?

**Comment by dragen1860** [comment]
yes, i move away the `metalearner` and `learner` code, which is well-written architecture for that version. You can still access previous version from https://github.com/dragen1860/Reptile-Pytorch. 
Sorry for making it confuous. 
Im working on memory mechanism and thereby MAML related research is interrupted temporarily.

**Comment by dragen1860** [comment]
Hi, I hv fixed current version bugs, u can pull latest version, which should works now on both omniglot and mini-imagenet.
