### ISSUE TITLE
It cost too much time for miniImageNet training.

### ISSUE THREAD

**Issue by AlloNighthawk** [dragen1860/MAML-Pytorch#20]
Hi

Thank you for sharing your code.

I cloned your code and ran the miniImageNet training, and it took 2497 seconds, which is about 42 minutes, for 1000 steps with GTX 1080 Ti GPU. I also reduced the task nums to 2. The training time might be too expensive for me. 

I noticed the GPU-Util increased to 20-40% for about 1 second and decreased to 0% for a few seconds when training.

So I am wondering if the training time is acceptable.

**Comment by dragen1860** [comment]
Hi, I forget the time elapsed. But usually i could tell your time cost is sort of slow.
