### ISSUE TITLE
how can i train on multi-gpus

### ISSUE THREAD

**Issue by yanglilian** [dragen1860/MAML-Pytorch#21]
can you show me some sample code

**Comment by RongKaiWeskerMA** [comment]
what I found was that even if you use one gpu, the training speed is as slow as using cpu, I am not sure if multi-gpu help, because most of the time the program was running on cpu I guess

**Comment by dragen1860** [comment]
Hi, since MAML is involed in 2nd order derivative, it's common to see very slow compared with general supervised learning.

**Comment by jqnap** [comment]
May I know how long it takes to train omniglot dataset to 40000 epochs?
