### ISSUE TITLE
why is the entire model being updated during the train phase of meta training?

### ISSUE THREAD

**Issue by sudarshan1994** [dragen1860/MAML-Pytorch#22]

**Comment by sudarshan1994** [comment]
The entire model is getting updated in the train phase of the meta training, but should'nt just the final layer get updated, while the of rest of the network  gets updated during the test phase of meta training ?

**Comment by dragen1860** [comment]
NO. you may refer to the original paper for more algorithm mechnism details.

**Comment by dongzhuoyao** [comment]
Still doubt here
