### ISSUE TITLE
Should I fine-tune the model on each new task

### ISSUE THREAD

**Issue by AaboutL** [dragen1860/MAML-Pytorch#30]
If I get a new task, should I fine-tune the trained model on this new task?

**Comment by dragen1860** [comment]
Yes, according to MAML setting, you should fine tunning it and then predict.

**Comment by XA23i** [comment]
> Yes, according to MAML setting, you should fine tunning it and then predict.

hello, i have read the paper several times. However i can't find where it says we should fine-tune the model when testing.
