### ISSUE TITLE
Batch running statistics being updated at validation time

### ISSUE THREAD

**Issue by AntreasAntoniou** [dragen1860/MAML-Pytorch#4]
In line 340 of the maml.py file you use:
```
pred = self.net(support_x[i])
```
Which makes training to default to True. Do we really want the batch running stats to be updated at inference time?

**Comment by dragen1860** [comment]
Hi, About this problem, setting it to True or False does not have too much difference, if i not wrong.
Especially for meta-learning problem, the meta-train includes  2 sub stages: training and test, so is meta-test.
Hence, I found it obscure to set the flag to True or False for meta-learning problem.
