### ISSUE TITLE
Why not "loss_q = sum(losses_q) / task_num" ?

### ISSUE THREAD

**Issue by geekyutao** [dragen1860/MAML-Pytorch#51]
Hi, thanks for your codes!
I think the line 134 "loss_q = losses_q[-1] / task_num" in meta.py should be "loss_q = sum(losses_q) / task_num". What do you think of it?

**Comment by chocoford** [comment]
@geekyutao Here's what I think.
For every task, the k's `losses_q` is the final loss after `update_step` calculations.
Actually, the `losses_q[-1]` is the sum of losses of all tasks.

**Comment by geekyutao** [comment]
Thanks for your hint！I will close the issue.
