### ISSUE TITLE
Is it appropriate to update the parameters of meta-learner during testing?

### ISSUE THREAD

**Issue by philip-pan** [dragen1860/MAML-Pytorch#6]
While testing, your code still updates the parameters of meta-learner.

**Comment by dragen1860** [comment]
hi, thanks. I have make a modification: https://github.com/dragen1860/MAML-Pytorch/blob/69c08a02b953dcfc3205962f42985f751afb5057/maml.py#L399

**Comment by philip-pan** [comment]
The accuracy of your implementation after modification drops by 10 percent in the experiment of 5-way 1-shot setting on miniImageNet dataset.
